//USAREMOS O LET
//PODE-SE UTILIZAR CAMELCASE
//NÃO PODEMOS CRIAR VARIÁVEIS COM PALAVRAS RESERVADAS DA LINGUAGEM 
//PRECISAM DE NOMES SIGNIFICATIVOS
//NÃO PODE COMEÇAR COM NÚMEROS
//NÃO PODE TER ESPAÇOS OU TRAÇOS


let nome = 'João'; //STRING
console.log(nome + 'nasceu em 2003');